//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class cuota
    {
        public int id { get; set; }
        [DisplayName("")]
        public int id_deuda { get; set; }
        [DisplayName("Saldo Inicial")]
        public decimal saldo_inicial { get; set; }
        [DisplayName("Interes")]
        public decimal interes { get; set; }
        [DisplayName("Cuota")]
        public decimal monto_cuota { get; set; }
        [DisplayName("Amortización")]
        public decimal amortizacion { get; set; }
        [DisplayName("Seguro riesgo")]
        public decimal seguro_riesgo { get; set; }
        [DisplayName("Recompra")]
        public decimal recompra { get; set; }
        [DisplayName("Comision")]
        public decimal Comision { get; set; }
        [DisplayName("Saldo Final")]
        public decimal saldo_final { get; set; }
        [DisplayName("Depreciación")]
        public decimal depreciacion { get; set; }
        [DisplayName("Ahorro Tributario")]
        public decimal ahorro_tributario { get; set; }
        [DisplayName("IGV")]
        public decimal IGV { get; set; }
        [DisplayName("Flujo Bruto")]
        public decimal f_bruto { get; set; }
        [DisplayName("Flujo con IGV")]
        public decimal f_igv { get; set; }
        [DisplayName("Flujo Neto")]
        public decimal f_neto { get; set; }
        [DisplayName("¿Tiene P.G?")]
        public bool PeriodoGracia { get; set; }
        [DisplayName("¿Cancelado?")]
        public bool Pagado { get; set; }
        public System.DateTime Fecha_De_Pago { get; set; }
    
        public virtual Deuda Deuda { get; set; }
    }
}
