//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Finanzas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasEntitiesContext : DbContext
    {
        public FinanzasEntitiesContext()
            : base("name=FinanzasEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tipo_usuario> Tipo_usuario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Periodo_gracia> Periodo_gracia { get; set; }
        public virtual DbSet<Bien> Biens { get; set; }
        public virtual DbSet<cuota> cuotas { get; set; }
        public virtual DbSet<Deuda> Deudas { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    }
}
