//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Periodo_gracia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodo_gracia()
        {
            this.Deudas = new HashSet<Deuda>();
        }
    
        public int id { get; set; }
        [DisplayName("Tipo de P.G")]
        public string Descripcion { get; set; }
        public int Tiempo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deuda> Deudas { get; set; }
    }
}
