//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Biens = new HashSet<Bien>();
        }
    
        public int id { get; set; }
        [DisplayName("Razon Social")]
        public string nombre { get; set; }
        [DisplayName("RUC")]
        public long RUC { get; set; }
        [DisplayName("E-Mail")]
        public string correo { get; set; }
        [DisplayName("Password")]
        public string contraseña { get; set; }
        [DisplayName("Cliente")]
        public int idTipoUsuario { get; set; }
    
        public virtual Tipo_usuario Tipo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bien> Biens { get; set; }
    }
}
